### ISSUE TITLE
No commands work when i give players there ranks

### ISSUE THREAD

**Issue by LilKitten23** [PEXPlugins/PermissionsEx#2735]
**] Edit by Stormbow: Moved permissions.yml file contents to [Pastebin](http://pastebin.com/rvKpNGhi). [**

**Comment by Stormbow** [comment]
Most of your file doesn't follow [this official example file](http://pastebin.com/8ZSHxauG).  I fixed most of what you had to follow that format, [right here](http://pastebin.com/CmEvvjKS).

A couple other major problems that I noticed which will affect other plugins:

• You have **_a lot_** of permission nodes in your file that do not exist.  You need to look at the documentation for the plugins you're using to find out what their _actual_ permission nodes are.  **I didn't remove any of the fake/non-existent permission nodes.  This gives you a list of permissions t go find and learn if they're real or not.**

• Your "Co-Owner" group name should be changed to "CoOwner" because some plugins will not recognize a group named "Co-Owner" (because of the hyphen).  **I fixed this in the correction I linked to you up above.**

• Your entire users section was a train wreck, so I removed everyone.  It will be easier to reassign people to groups than to delete all the mistakes and get everyone situated correctly.

Once you have rejoined the server, type `pex user YourMinecraftName add permissions.*` to give yourself (**and only yourself**) full access to all of the PEX commands on the server, no matter which group you are in.  This will help you to move yourself around to different groups on the server while you are setting up and testing things.  _Don't give this permission to **any** other player because you will be giving them the power to delete your entire permissions system._

**Comment by LilKitten23** [comment]
I put this into my permissions file and saved it and started the server up i did what you said then gave a player trusted but they still cant do /tp or /help

**Comment by LilKitten23** [comment]
Abag, AbilityTrader, OpTalk, Admin Essentials, GriefAlert, AdminColorChat, AdminNotes, Bssentials GroupManager, EssentialsX, Grief Prevention, PermissionsEx, PermissionsExTabColors, 
SetRankPEX, Vault and WorldEdit, these are my plugins

**Comment by Stormbow** [comment]
> I put this into my permissions file and saved it and started the server up i did what you said then gave a player trusted but they still cant do /tp or /help

Did you read the plugin documentation to verify the group has the correct permissions?

----

• You should not use multiple "essentials" plugins (Admin Essentials, Bssentials, and EssentialsX).  EssentialsX is the best of all of them.

• You should not use multiple chat coloring plugins.  (AdminColorChat, EssentialsXChat)  EssentialsX ([EssentialsXChat](http://ci.drtshock.net/job/essentialsx/)+[Vault](http://dev.bukkit.org/bukkit-plugins/vault/), actually) does it better.

♦ You **_can't_** use GroupManager and PermissionsEx— they're both permissions handling plugins.  (And I may be biased, but PermissionsEx is the best.)

----

**Comment by LilKitten23** [comment]
I will try to do what you said and i have removed the un needed plugins from my server

**Comment by Stormbow** [comment]
Post here again after you've had time to test things out.

**Comment by LilKitten23** [comment]
18.03 00:34:42 [Server] ERROR Permission node 'users' in permissions.yml is invalid
18.03 00:34:42 [Server] ERROR Permission node 'schema-version' in permissions.yml is invalid
18.03 00:34:42 [Server] WARN Version mismatch! Please update all Essentials jars to the same version.

**Comment by LilKitten23** [comment]
this was in the console after a restart

**Comment by LilKitten23** [comment]
groups:
  Player:
    options:
      default: 'true'
      prefix: '&a[Guest] &f'
      build: 'true'
    inheritance: []
    permissions:
    - essentials.afk
    - essentials.delhome
    - essentials.fly
    - essentials.help
    - essentials.home
    - essentials.helpop
    - essentials.kit
    - essentials.mail
    - essentials.motd
    - essentials.msg
    - essentials.r
    - essentials.realname
    - essentials.recipe
    - essentials.rules
    - essentials.sethome
    - essentials.showkit
    - essentials.suicide
    - essentials.tp
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp
    - griefprevention.abandonclaim
    - griefprevention.abandonallclaims
    - griefprevention.trust
    - griefprevention.untrust
    - griefprevention.containertrust
    - griefprevention.accesstrust
    - griefprevention.permissiontrust
    - griefprevention.extendclaim
    - griefprevention.claim
    - griefprevention.trustlist
    - griefprevention.claimlists
    - griefprevention.givepet
    - griefprevention.claimbook
  Trusted:
    options:
      prefix: '&2[Trusted] &f'
      default: 'false'
      build: 'true'
    inheritance:
    - Player
    permissions:
    - essentials.gamemode
    - griefprevention.subdivideclaims
    - griefprevention.
    - griefprevention.
  Admin:
    option:
      prefix: '&b[Admin] &f'
      default: 'false'
      build: 'true'
    inheritance:
    - Trusted
    permissions:
    - essentials.broadcast
    - essentials.burn
    - essentials.clearinventory
    - essentials.ext
    - essentials.feed
    - essentials.give
    - essentials.hat
    - essentials.heal
    - essentials.invsee
    - essentials.item
    - essentials.jails
    - essentials.kick
    - essentials.kill
    - essentials.nick
    - essentials.socialspy
    - essentials.sudo
    - essentials.tempban
    - essentials.time
    - essentials.tphere
    - essentials.weather
    - essentials.vanish
    - AdminNotes.notes
    - AdminNotes.notes
    - AdminNotes.notes.append
    - AdminNotes.notes.create
    - AdminNotes.notes.info
    - AdminNotes.notes.list
    - AdminNotes.notes.modify
    - AdminNotes.notes.notify
    - AdminNotes.notes.remove
    - AdminNotes.notes.search
    - OpTalk.ac
    - OpTalk.fsay
    - griefprevention.setaccruedclaimblocks
    - griefprevention.deleteclaim
    - griefprevention.deleteclaims
    - griefprevention.adminclaims
    - griefprevention.ignoreclaims
    - griefprevention.transferclaim
  CoOwner:
    options:
      prefix: '&6[&4Owner&6] &f'
      default: 'false'
      build: 'true'
    inheritance: []
    permissions:
    - '*'
  Owner:
    options:
      prefix: '&9[Owner] &f'
      default: 'false'
      build: 'true'
    inheritance: []
    permissions:
    - '*'
schema-version: 1
users:
  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
    options:
      name: LilKitten_
    group:
    - Owner
    permissions:
    - permissions.*

**Comment by LilKitten23** [comment]
18.03 02:19:24 [Server] ERROR Permission node 'schema-version' in permissions.yml is invalid
only error now

**Comment by LilKitten23** [comment]
18.03 02:24:41 [Server] INFO Debug mode for user Stormbow/Stormbow enabled!
18.03 02:24:11 [Server] INFO Error in command syntax. Check command help.
18.03 02:23:46 [Server] INFO The_Muffin_Guy was denied access to command.
18.03 02:23:23 [Server] INFO The_Muffin_Guy was denied access to command.
18.03 02:23:05 [Server] INFO Debug mode for user Stormbow/Stormbow enabled!
18.03 02:22:13 [Server] INFO The_Muffin_Guy was denied access to command.
18.03 02:21:47 [Server] INFO The_Muffin_Guy was denied access to command.

**Comment by LilKitten23** [comment]
18.03 02:26:20 [Server] INFO User f30ebd61-d7d7-4dd4-97cd-1a7ac39c36d8 checked for "worldedit.limit.unrestricted", no permission found
18.03 02:26:20 [Server] INFO User f30ebd61-d7d7-4dd4-97cd-1a7ac39c36d8 checked for "worldedit.limit.unrestricted", no permission found
18.03 02:26:14 [Server] INFO The_Muffin_Guy was denied access to command.
18.03 02:26:03 [Server] INFO Debug mode for user f30ebd61-d7d7-4dd4-97cd-1a7ac39c36d8/The_Muffin_Guy enabled!

**Comment by Stormbow** [comment]
The permissions.yml file [parses](http://yaml-online-parser.appspot.com/) cleanly.  What seems to be the problem?

**Comment by LilKitten23** [comment]
they cant use the commands in the server, it says you dont have permission to use this command i have done /pex user The_Muffin_Guy group add player

**Comment by Stormbow** [comment]
Have you added those missing permissions that you found when using Debug Mode to the group he is in?

**Comment by LilKitten23** [comment]
they are all there
he tried using tp and help

**Comment by Stormbow** [comment]
Show me the full debug output of the command(s) which are not working.

**Comment by LilKitten23** [comment]
[new format.txt](https://github.com/PEXPlugins/PermissionsEx/files/852379/new.format.txt)

**Comment by LilKitten23** [comment]
hes offline now i cant until in the morning

**Comment by Stormbow** [comment]
Put yourself in the group he was in, test the command.  That's why we gave you (specifically, directly) the `permissions.*` node— you can `pex user LilKitten_ group set HisGroupName` and then test the command that isn't working in his group.

**Comment by LilKitten23** [comment]
i will do that in the morning its 11pm

**Comment by LilKitten23** [comment]
All the commands work for me being in the player group and deopped, so why arent they working for him?

**Comment by EmanYm** [comment]
Do you have default=1 set on yourself?

**Comment by LilKitten23** [comment]
Can you add me on Discord maybe you could go into the console and help me, im ready to give up :c 
LilKitten#2906

**Comment by Stormbow** [comment]
> Do you have default=1 set on yourself?

This is not a PEX setting.  Do not do this.

> deopped

Avoid using OP because OP is for "Vanilla" servers which have no plugins at all.

> All the commands work for me being in the player group and deopped, so why arent they working for him?

He must be entering the commands incorrectly.

**Comment by Stormbow** [comment]
> LilKitten#2906

I sent you a friend request.

**Comment by Stormbow** [comment]
Problems all solved!  :D

The server was using the root directory's permissions.yml file instead of the /plugins/PermissionsEx/permissions.yml file.

**Comment by Stormbow** [comment]
Feel free to post here again if you run into any other PEX/permission problems. :)

**Comment by LilKitten23** [comment]
hey stormbow do you have a copy of the permissions i used

**Comment by Stormbow** [comment]
Sorry, no.  I don't keep anything, and I usually make pastes I do for people have a 1 month duration, so their stuff is more likely to remain their stuff.

**Comment by LilKitten23** [comment]
damn im re setting up a server for friends and i didnt want to have to do
it from scratch again

**Comment by Stormbow** [comment]
A few posts up, in this thread, there's one of your older posts with a permissions file in it...

**Comment by Stormbow** [comment]
Click View it on GitHub in the email you're replying to.

**Comment by LilKitten23** [comment]
okay

**Comment by LilKitten23** [comment]
03.07 20:27:10 [Server] ERROR Permission node 'schema-version' in
permissions.yml is invalid
https://pastebin.com/DEnCqTZH

**Comment by Stormbow** [comment]
Corrected:  https://pastebin.com/jbNex6VS

**Comment by LilKitten23** [comment]
thank you very much

**Comment by LilKitten23** [comment]
https://pastebin.com/amcVynS9

**Comment by Stormbow** [comment]
> 04.07 19:40:30 [Server] ERROR Permission node 'users' in permissions.yml is invalid

Show me the latest file.  :x

**Comment by Stormbow** [comment]
Keep in mind that the version of a plugin should match the version of the server.  For example GriefAlert 2.3 (from 2013) is for Minecraft 1.6.2, and you're attempting to run a 1.12 server.  :x

**Comment by Stormbow** [comment]
(I didn't look at all the other version matching; GriefAlert caught my interest and I looked it up because I'd never heard of it.  Now I know why—  LOL —it's _ancient_.)

**Comment by LilKitten23** [comment]
do you want to take a look i can give you my logins

**Comment by Stormbow** [comment]
I'll get on my PEX Discord.  :)

**Comment by LilKitten23** [comment]
some of my player commands arent working and i cant seem to get mcmmo set up

**Comment by Stormbow** [comment]
Which commands?

What were you trying to set up in mcMMO?

**Comment by Stormbow** [comment]
mcMMO is installed now.  You just have to distribute the [permission nodes](https://github.com/mcMMO-Dev/mcMMO/wiki/List-of-permissions).

**Comment by LilKitten23** [comment]
hey stormbow

**Comment by Stormbow** [comment]
hey lilkitten23

**Comment by Stormbow** [comment]
I forgot that comments in tickets doesn't bump the ticket to the front page, so there's no point having this open. heh  Oh well.  I still get 'em in email.

**Comment by LilKitten23** [comment]
I need help, warps arent working and ive added them for players to use also
i changed the amount of homes anf that wont work either

**Comment by LilKitten23** [comment]
thank you for fixing it

**Comment by Stormbow** [comment]
I posted 2 days ago that I am out of town for my anniversary.
If you posted from the PEX site, you would have seen that and might not be posting such a rude comment when no one teplied to your ticket.
----
Posted from my Samsung Galaxy S5.

-------- Original message --------

**Comment by LilKitten23** [comment]
wait who fixed it then?

**Comment by Stormbow** [comment]
I don't know what the issue was really, nor who (if anyone) fixed it.  I deleted all of the information for your server (on Discord) immediately after I no longer needed it, after we last worked on the server together.

I'm glad to hear it's fixed, whatever it was. Maybe you're better at this than you give yourself credit for.  :-)

**Comment by LilKitten23** [comment]
you are welcome to add me on discord again if you like Angel Pup 🐾#7337
